### ISSUE TITLE
LSM6DSM aygıtının verileri okunamıyor.

### ISSUE THREAD

**Issue by oraknorak** [deneyapkart/deneyapkart-platformio-core#1]
LSM6DSM 3-Eksen Dönüölçer ve 3-Eksen İvmeölçer aygıtının sağladığı veriler Arduino IDE ile derlenip yüklendiğinde okunabiliyor fakat PlatformIO ile derlenip yüklendiğinde okunamıyor.

`#define LSM6DSM_WHO_AM_I  0x0F  // should be 0x6A`

ile tanımlanan kayıt okunduğunda 0x6A yerine 0x3F dönüyor.

0x20 ile 0x2D arasında okunan 7 bayt veri şöyle:
0,0,172,63,13,128,144

**Comment by ozgurbostan** [comment]
Merhaba,

Deneyap Kart PlatformIO Platformu ile hazır gelen "lsm6dsm" kütüphanesini kullanarak yaptığım deneme neticesinde bahsetmiş olduğunuz sorun ile karşılaşmadım. Acaba tam olarak nasıl bir sorun yaşıyorsunuz? Kod vb. paylaşımlar yaparak detaylandırabilirsiniz süreci.

Hata kaydı oluştururken hazır şablonu (Hata raporu) kullanabilirseniz daha sağlıklı bir süreç yürütmüş oluruz.

**Comment by oraknorak** [comment]
Henüz PlatformIO için yayınlanmamışken https://github.com/kriswiner/LSM6DSM_LIS2MDL_LPS22HB/blob/master/LSM6DSM.cpp adresindekini kullanmıştım. PlatformIO'ya aktarırken 0 ve 1. pinleri INPUT olarak belirtilen yapılandırıcı fonksiyonu atlamışım.

Bu kaydı açmakta biraz acele etmişim.

Adresteki dosyada sizin kullandığınız

Wire.begin(IMUSD, IMUSC, 0);

yerine yapılandırıcıda 0 ve 1. pinler INPUT olarak belirtiliyor. Siz COMMON_SDA ve COMMON_SCL kullanmışsınız. Bunu da sonra bir ara öğreniriz.

Konuyla alakalı değil ama benim kullandığımda sapmaları hesaplayan ve değerleri düzeltmek için kullanan bölüm var.  Deneyap Kart'a eklenebilir. Dana sonra foruma yazarım.
