### ISSUE TITLE
analogWrite is missing

### ISSUE THREAD

**Issue by Aerodymier** [deneyapkart/deneyapkart-platformio-core#3]
### Hardware:
Board | : | Deneyap Kart
----- | - | ------------
Core version | : | 1.0.0+sha.e231d85
IDE | : | PlatformIO
Computer OS | : | Windows 11 Pro
Upload mode | : | auto
Upload speed | : | 11600
CPU frequecny | : | 240MHz
Flash frequency | : | 40MHz
Flash mode | : | qio
Partition scheme | : | default

### Description:
analogWrite behavior is missing but can be wrapped up with library support. 

### Expected behavior:
analogWrite should work like Arduino. Current methods might be a bit hard to understand for beginners and might need assistance from third parties. A wrapper for analogWrite for library would be really problem-solving.

Just realized that analogWrite I used was in ESP32Servo library. That can be directly imported as well. It works as expected.

**Comment by MelihOzbk** [comment]
You can add this code in the 'platformio.ini' file for fix your issue 
```
lib_deps=
  https://github.com/MelihOzbk/DeneyapKartPWM
```
example use,
```
[env:deneyapkart]
platform = deneyap
board = deneyapkart
framework = arduino

lib_deps=
  https://github.com/MelihOzbk/DeneyapKartPWM
```

**Comment by Aerodymier** [comment]
Thanks
